services:
  prometheus:
    image: grafana/grafana
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "8080:9090"

  node_exporter:
    image: prom/node-exporter
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'